address_table:
    path:   admin6833/address/table
    defaults: {_controller: Dywee\AddressBundle\Controller\SuperAdminAddressController::tableAction}

address_add:
    path:   admin6833/address/add
    defaults: {_controller: Dywee\AddressBundle\Controller\SuperAdminAddressController::addAction}

address_update:
    path:   admin6833/address/{id}/update
    defaults: {_controller: Dywee\AddressBundle\Controller\SuperAdminAddressController::updateAction}
    requirements:
        id: \d+
    options:
        expose: true

address_json:
    path:   admin6833/address/json/{id}
    defaults: {_controller: Dywee\AddressBundle\Controller\SuperAdminAddressController::jsonAction, id: null}
    options:
        expose: true
    requirements:
        id: \d+