##############################
#           USER             #
##############################


##############################
#           ADMIN            #
##############################


##############################
#        SUPER ADMIN         #
##############################

address_table:
    path:   admin6833/address/table
    defaults: {_controller: DyweeAddressBundle:SuperAdminAddress:table}

address_view:
    path:   admin6833/address/{id}
    defaults: {_controller: DyweeAddressBundle:SuperAdminAddress:view}
    requirements:
        id: \d+
    options:
        expose: true

address_add:
    path:   admin6833/address/add
    defaults: {_controller: DyweeAddressBundle:SuperAdminAddress:add}

address_update:
    path:   admin6833/address/{id}/update
    defaults: {_controller: DyweeAddressBundle:SuperAdminAddress:update}
    requirements:
        id: \d+
    options:
        expose: true

address_delete:
    path:   admin6833/address/{id}/delete
    defaults: {_controller: DyweeAddressBundle:SuperAdminAddress:delete}
    requirements:
        id: \d+

address_json:
    path:   admin6833/address/json/{id}
    defaults: {_controller: DyweeAddressBundle:SuperAdminAddress:json, id: null}
    options:
        expose: true
    requirements:
        id: \d+