##############################
#           USER             #
##############################


##############################
#           ADMIN            #
##############################


##############################
#        SUPER ADMIN         #
##############################

superAdmin_address_table:
    path:   admin6833/address/table
    defaults: {_controller: DyweeAddressBundle:SuperAdminAddress:table}

superAdmin_address_view:
    path:   admin6833/address/{id}
    defaults: {_controller: DyweeAddressBundle:SuperAdminAddress:view}
    requirements:
        id: \d+
    options:
        expose: true

superAdmin_address_add:
    path:   admin6833/address/add
    defaults: {_controller: DyweeAddressBundle:SuperAdminAddress:add}

superAdmin_address_update:
    path:   admin6833/address/{id}/update
    defaults: {_controller: DyweeAddressBundle:SuperAdminAddress:update}
    requirements:
        id: \d+
    options:
        expose: true

superAdmin_address_delete:
    path:   admin6833/address/{id}/delete
    defaults: {_controller: DyweeAddressBundle:SuperAdminAddress:delete}
    requirements:
        id: \d+

superAdmin_address_json:
    path:   admin6833/address/json/{id}
    defaults: {_controller: DyweeAddressBundle:SuperAdminAddress:json, id: null}
    options:
        expose: true
    requirements:
        id: \d+

superAdmin_address_test_response:
    path:   admin6833/test1/response
    defaults: {_controller: DyweeAddressBundle:SuperAdminAddress:indexResults}
    options:
        expose: true