dywee_address_admin_table:
    path:     /admin6833/address/table
    defaults: { _controller: DyweeAddressBundle:Admin:table }

dywee_address_admin_add:
    path:     /admin6833/address/add
    defaults: { _controller: DyweeAddressBundle:Admin:add }

dywee_address_admin_view:
    path:     /admin6833/address/view/{id}
    defaults: { _controller: DyweeAddressBundle:Admin:view }
    requirements:
        id: \d+

dywee_address_admin_update:
    path:     /admin6833/address/update/{id}
    defaults: { _controller: DyweeAddressBundle:Admin:update }
    requirements:
            id: \d+

dywee_address_admin_delete:
    path:     /admin6833/address/delete/{id}
    defaults: { _controller: DyweeAddressBundle:Admin:delete }
    requirements:
            id: \d+

dywee_address_user_table:
    path:     /admin/address/table
    defaults: { _controller: DyweeAddressBundle:User:table }

dywee_address_user_add:
    path:     /admin/address/add
    defaults: { _controller: DyweeAddressBundle:User:add }

dywee_address_user_view:
    path:     /admin/address/view/{id}
    defaults: { _controller: DyweeAddressBundle:User:view }
    requirements:
        id: \d+

dywee_address_user_update:
    path:     /admin/address/update/{id}
    defaults: { _controller: DyweeAddressBundle:User:update }
    requirements:
            id: \d+

dywee_address_user_delete:
    path:     /admin/address/delete/{id}
    defaults: { _controller: DyweeAddressBundle:User:delete }
    requirements:
            id: \d+