services:

    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: true

    Dywee\AddressBundle\:
        resource: '../../*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../{DependencyInjection,Entity,Event,Listener,Repository,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    Dywee\AddressBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    dywee_address.admin_sidebar_listener:
        class: Dywee\AddressBundle\Listener\AdminSidebarBuilderListener
        arguments: [ '@dywee_address.sidebar_handler' ]
        tags:
            - { name: kernel.event_subscriber }

    dywee_address.sidebar_handler:
        class: Dywee\AddressBundle\Service\AdminSidebarHandler
        arguments: [ '@router' ]

    dywee_address.form_handler:
        class: Dywee\AddressBundle\Service\FormHandler
        arguments: ['@form.factory', '@doctrine.orm.entity_manager']