services:

    dywee_address.admin_sidebar_listener:
        class: Dywee\AddressBundle\Listener\AdminSidebarBuilderListener
        arguments: [ '@dywee_address.sidebar_handler' ]
        tags:
            - { name: kernel.event_subscriber }

    dywee_address.sidebar_handler:
        class: Dywee\AddressBundle\Service\AdminSidebarHandler
        arguments: [ '@router' ]

    dywee_address.form_handler:
        class: Dywee\AddressBundle\Service\FormHandler
        arguments: ['@form.factory', '@doctrine.orm.entity_manager']