<?php

namespace Dywee\AddressBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository
{
    public function findAllForPagination($website)
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.website = :website')
            ->setParameter('website', $website)
            ;

        return $qb;
    }

    public function getByRecent($website)
    {
        return $this
            ->createQueryBuilder('a')
            ->orderBy('a.id', 'desc')
            ->where('a.website = :website')
            ->setParameter('website', $website)
            ;
    }

    public function getSelectList($website)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.website = :website')
            ->setParameter('website', $website)
            ->orderBy('a.lastName', 'asc')
        ;

        return $qb;
    }
}
