<?php

namespace Dywee\AddressBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository
{
    public function findAllForPagination()
    {
        $qb = $this->createQueryBuilder('a');

        return $qb;
    }

    public function getByRecent()
    {
        return $this
            ->createQueryBuilder('a')
            ->orderBy('a.id', 'desc')
            ;
    }
}
